DROP DATABASE IF EXISTS `Journal`;
CREATE DATABASE `Journal`;
USE `Journal`;
CREATE TABLE `authors` (
	`id` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`surname` VARCHAR (50) NOT NULL
);

CREATE TABLE `reviewers` (
	`id` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR (50) NOT NULL,
	`surname` VARCHAR (50) NOT NULL
);

CREATE TABLE `issues` (
	`id` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`date` DATE
);

CREATE TABLE `articles` (
	`id` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR (150) NOT NULL,
	`author` INTEGER AUTO_INCREMENT NOT NULL,
	`reviewer` INTEGER AUTO_INCREMENT NOT NULL,
	`accepted` TINYINT(1) NOT NULL,
	`issue` INTEGER AUTO_INCREMENT NOT NULL,
	FOREIGN KEY (`author`) REFERENCES `authors`(`id`),
	FOREIGN KEY (`reviewer`) REFERENCES `reviewers`(`id`),
	FOREIGN KEY (`issue`) REFERENCES `issues`(`id`)
);

